name: lunaris_engine
description: "The largest library of algorithms in the Dart language, and soon globally, includes an arsenal of 300 algorithms, including machine learning, networks, encryption algorithms, blockchain, and much more."# algorithm,# data structures
version: 0.1.6
repository: https://github.com/Darklunaris/lunaris_engine
homepage: https://pofk.vercel.app/
environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  benchmark_harness: ^2.3.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

license: MIT

# algorithm
# algorithms
# lunaris_engine
# data structures
# linked lists
# trees
# graphs
# search
# sort
# string
# set
# map
# AI
# helpers
# utilities
# common
# flutter
# web
# mobile
# desktop
# server
# cloud
# microservices
# APIs
# integration